<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
        <FablePackageType>library</FablePackageType>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>3239;0025;3261</WarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>Oxpecker DSL and Datastar attributes for authoring Rocket components with Fable</Description>
        <Version>0.1.0-beta.1</Version>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="../Oxpecker.ViewEngine/IdeTweaks.fs" Link="IdeTweaks.fs" />
        <Compile Include="Tools.fs" />
        <Compile Include="../Oxpecker.ViewEngine/Builder.fs" Link="Builder.fs" />
        <Compile Include="../Oxpecker.ViewEngine/Tags.fs" Link="Tags.fs" />
        <Compile Include="../Oxpecker.ViewEngine/Aria.fs" Link="Aria.fs" />
        <Compile Include="Render.fs" />
        <Compile Include="../Oxpecker.Datastar/Helpers.fs" Link="Helpers.fs" />
        <Compile Include="../Oxpecker.Datastar/Attributes.fs" Link="Attributes.fs" />
        <Compile Include="../Oxpecker.Datastar/Pro.fs" Link="Pro.fs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FSharp.Core" Version="10.0.100" />
        <PackageReference Include="Fable.Core" Version="5.0.0" />
        <PackageReference Include="Fable.Package.SDK" Version="1.3.2" PrivateAssets="all" />
    </ItemGroup>
</Project>
